### ISSUE TITLE
Plugin stop working after repl restart

### ISSUE THREAD

**Issue by cedrictools** [venantius/vim-cljfmt#11]
Great plugin!
Everything works fine until I stop lein repl and start a new one.
Once the new repl instance is started, fireplace will connect to the new port and I can still evaluate code. However for this plugin to work it seems that I have to restart vim ?

**Comment by venantius** [comment]
Yeah, this was by design to keep Vim from constantly `require`ing the cljfmt namespace; especially since most developers don't restart their REPL very often. The relevant bit of code is the global variable `let g:clj_fmt_required = 1`. 

On the one hand, I feel like modifying the code to always require the cljfmt ns might be un-necessary overhead. On the other hand, it's not a lot of overhead.

**Comment by cedrictools** [comment]
Thanks, I did comment that line 
https://github.com/venantius/vim-cljfmt/blob/master/plugin/cljfmt.vim#L11
Works perfect now, the overhead on my machine isn't really noticeable.
Agree would be better not to restart the repl at all ;)
