### ISSUE TITLE
datomic datalog query indentation

### ISSUE THREAD

**Issue by chadhs** [venantius/vim-cljfmt#25]
when experimenting with datomic…

this

``` clojure
(d/q '[:find ?owner-name
       :where [?dog :dog/name "Tiny"]
              [?owner :owner/dogs ?dog]
              [?owner :owner/name ?owner-name]]
     (d/db conn))
```

becomes

``` clojure
(d/q '[:find ?owner-name
       :where [?dog :dog/name "Tiny"]
       [?owner :owner/dogs ?dog]
       [?owner :owner/name ?owner-name]]
     (d/db conn))
```

**Comment by venantius** [comment]
This is likely to be an upstream behavior. Have you checked to see if `cljfmt` by itself does this?

**Comment by venantius** [comment]
The corrected indentation here is the right / expected one.

**Comment by chadhs** [comment]
@venantius most of the datomic datalog examples i've seen all have the `:where` conditions aligned, which seems more readable to me.

i can imagine accounting for every scenario is monumental task, and perhaps this is something i could be asking about at the cljfmt project level?

Btw, this plugin coupled with electric return option in paredit make my vim clojure experience near magical.  thnx!

**Comment by venantius** [comment]
@chadhs are you sure those examples don't have the where conditions nested in their own vector?

**Comment by chadhs** [comment]
Tried that and seemed to cause 'splosions 😔

**Comment by venantius** [comment]
Gotcha. I took a look at the Datomic docs and it seems you're right, they don't belong in the vector.

That having been said, the alignment you're getting from vim-cljfmt is the expected alignment for these data structures. I'd verify that with the `lein-cljfmt` plugin first and raise an issue with weavejester if you want to bring it up to him. I think cljfmt might support configuration for the sort of indentation you want to do -- if that turns out to be the case, this issue would then support https://github.com/venantius/vim-cljfmt/issues/24

**Comment by chadhs** [comment]
:+1: thanks @venantius
