### ISSUE TITLE
Why does this plugin not perform like the clojure formatter?

### ISSUE THREAD

**Issue by rjb25** [venantius/vim-cljfmt#32]
[This answer](http://stackoverflow.com/a/17830491/4982354) is what I think many of us would like our formatted code to look like. Why is there a big difference between what vim-cljfmt does and what clojures built in fomatter does? Example of vim-cljfmt on a horrible one liner:
```
(defn prime? [n known](loop [cnt (dec (count known)) acc []](if (< cnt 0) (not (any? acc))                                                                                             (recur (dec cnt) (concat acc [(zero? (mod n (nth known cnt)))])))))
```
Oops, no change.
Let's try the clojure formatter from [that answer](http://stackoverflow.com/a/17830491/4982354):
```
(defn prime? [n known]
  (loop [cnt (dec (count known)) acc []]
    (if (< cnt 0)
      (not (any? acc))
      (recur
        (dec cnt)
        (concat acc [(zero? (mod n (nth known cnt)))])))))
```
OOOH nice standardized classy line breaking and formatting.
All joking aside, might you be able to point me to a vim plugin that has this behavior or steer this plugin to accomplish this? Possibly I missed a setting in this plugin that could do this?

**Comment by venantius** [comment]
This plugin inherits behavior from [cljfmt](https://github.com/weavejester/cljfmt), which is where the sort of configuration you are concerned with would need to be addressed.

The StackOverflow article you are referring to references `rewrite-clj`, which `cljfmt` is built on top of, and `clojure.pprint` (the built-in library). The latter, however, is a pretty-printer, not a code formatter. Of course, because Clojure is a lisp, code can be considered data, but the idiomatic community style has departures from "pretty-printed" code as opposed to properly formatted code (as an example of this, see https://github.com/bbatsov/clojure-style-guide#one-space-indent).

**Comment by rjb25** [comment]
Is there a vim plugin you know of that will prettify your code?

**Comment by venantius** [comment]
No. To be quite honest, I don't understand your use case. Why would you have code that looks like that one liner as part of a normal development process? 

And, if it's not part of a normal development process, why not just pipe it through `clojure.pprint` once and then use a normal code formatter?

**Comment by rjb25** [comment]
I often do not think about formatting while coding. So I am looking for something that will do it for me. That one liner is an exaggeration. More so just looking to standardize the look of my code so it looks nice. I will likely make a hack that pipes to clojure pprint if you do not know of anything that does this already.

**Comment by venantius** [comment]
I wish you the best of luck in doing so. I think you may run into an issue in parsing the code before passing it over to `clojure.pprint` in that unless you quote it you'll need to run it through `read-string` or `eval` and that may potentially cause issues for you, but I imagine so long as your files' `ns` forms are properly configured it should all work.
