### ISSUE TITLE
Using a dedicated REPL apart from my project REPLs

### ISSUE THREAD

**Issue by yatesco** [venantius/vim-cljfmt#38]
I expect this is more of a `vim-fireplace` question but I would like to have a dedicated REPL purely for `clifmt` as well as REPLs for each project.

The benefit is that I don't need to start those project specific REPLs just to format the buffer.

Is this possible?

**Comment by venantius** [comment]
That is a really interesting question/feature request. You're right that this is at least in part a Fireplace question - what you want is to maintain two separate REPL connections at the same time. I think your request is valid but I wouldn't be surprised if Tim doesn't want to support something like this. You might end up having to fork Fireplace and run it under a different vim namespace in order to support a secondary REPL connection that would be exclusively for "background" purposes.

**Comment by yatesco** [comment]
Ah OK - that sounds like more work. My issue with the REPL is that I have some weird class path issue so refreshing all my code fails. Very weird, and maybe this is the perfect time to sort it out :-).

I will close this for now.
